### ISSUE TITLE
error while make on os x 10.10.5

### ISSUE THREAD

**Issue by cdolek** [TheZoc/sub3dtool#1]
cc -g -std=c99 -Wall -pedantic   -c -o src/main.o src/main.c
    cc -g -std=c99 -Wall -pedantic -c src/utils.c -o src/utils.o
    src/utils.c:227:2: error: use of undeclared identifier 'file'
            file = fopen(output, "w");
            ^
    src/utils.c:227:15: error: use of undeclared identifier 'output'
            file = fopen(output, "w");
                         ^
    2 errors generated.
    make: *** [src/utils.o] Error 1

**Comment by TheZoc** [comment]
Fixed it.  Try it and let me know how it goes, please :)

**Comment by cdolek** [comment]
it works like expected now, thank you.

**Comment by TheZoc** [comment]
I'm glad it works! If you run into any other problems, please report or submit a pull request and I'll try to fix ASAP :)
